version: '3.8'

services:

  postgres:
    image: postgres:10.5
    ports:
      - 5105:5432
    environment:
     - POSTGRES_DB=directory_data
     - POSTGRES_USER=chicommons
     - POSTGRES_PASSWORD=password
    volumes:
     - ./postgres/prod/db:/var/lib/postgresql/data

  web:
    restart: always
    build: ./web
    #env_file: .env
    environment:
     - DJANGO_SETTINGS_MODULE=directory.settings.prod
     - DB_HOST=postgres # host.docker.internal
     - DB_NAME=directory_data
     - DB_USER=chicommons
     - DB_PASS=password
     - DB_PORT=5432
    volumes:
     - uwsgi_socket_volume:/config/uwsgi/socket/
     - web_static_volume:/code/static/
    depends_on:
      - postgres 

  # client:
  #   restart: always
  #   build:
  #     context: ./client
  #   environment:
  #     - NODE_ENV=dockerdev
  #   volumes:
  #     - ./client:/app
  #   ports:
  #     - '3001:3000'
  #   container_name: web-app
  #   stdin_open: true
  #   command: /bin/bash /app/install_and_run.sh
  #   depends_on:
  #     - web

  nginx:
    image: nginx:1.23.1
    restart: always
    volumes:
     - ./nginx/:/etc/nginx/templates
     - uwsgi_socket_volume:/config/uwsgi/socket/
     - web_static_volume:/web-static/
    ports:
     - "80:80"
    depends_on:
      - web 

volumes:
  web_static_volume:
  uwsgi_socket_volume:
  client_static_volume: